### ISSUE TITLE
Implement dimming during ramping

### ISSUE THREAD

**Issue by geoffwatts** [geoffwatts/cbus2zigbee#12]
The transition feature on zigbee devices is implemented inconsistently, and zigbee2mqtt is so quick that it may make sense to implement something like the default event-script behaviour that sends new levels periodically during a ramp.

**Comment by autoSteve** [comment]
My only exposure to transitions are with Philips Hue devices, where my script instructs the bridge to tell the device to transition, and I monitor its progress using the event stream.

I've never been 100% happy with how it works, blaming the Hue bridge event stream for being laggy.

A different approach to transitions is probably warranted, telling the Zigbee device to transition at the start of a C-Bus ramp, and not sending the C-Bus state to Zigbee at the end of the ramp which is the current behaviour.

**Comment by autoSteve** [comment]
This experiment implements the transition /set at the beginning of a C-Bus ramp, and suppresses MQTT status for the expected duration of the ramp instead of a one-off ignoreMqtt.

How well it works will depend on how laggy status updates are from lights. If they come in after the ramp has finished, then C-Bus would get updated.

I think I read somewhere that it is possible to set a device option that could set the update frequency.

**Comment by autoSteve** [comment]
Thinking a bit further I think the payload to MQTT is probably wrong. I have it sending state as well as transition, and this probably needs more work. If state is 'OFF' and we want to transition to 50%, then I would imagine an 'ON' should be sent, but not for a transition from 50% to zero, which _would_ send a state of 'OFF' at the start of transition.

**Comment by autoSteve** [comment]
Here's what I read regarding Zigbee devices reporting updates.

[Koenkk](https://github.com/Koenkk)
[on Nov 23, 2021](https://github.com/Koenkk/zigbee2mqtt/discussions/9618#discussioncomment-1685810)
Maintainer
The proper way to do this is via reporting (a native feature which most devices should support). You can set it up via the frontend, click on your device -> reporting and set it up for cluster genLevelCtrl, attribute currentLevel, for change you could fill in 0, min 0 and max 1000.

An overview of which devices support reporting can be found here: https://www.zigbee2mqtt.io/guide/usage/binding.html#state-changes

**Comment by autoSteve** [comment]
Pushed a commit without referencing this issue. [Transitions evolved further](https://github.com/geoffwatts/cbus2zigbee/commit/38905d2fff7b3738a752a7ccc41b0a90b63f5380)

**Comment by autoSteve** [comment]
Did it again... 🤦🏻 [Mostly update comments](https://github.com/geoffwatts/cbus2zigbee/commit/c9ab83af75430b4f0bf0aaf79925447193c40106)

**Comment by autoSteve** [comment]
I should receive a networked Zigbee coordinator tomorrow, Geoff. When it arrives it is more going to be quiet whimpered relief given the timeframe, and not excitement...

I wish I had asked you about local suppliers earlier. The TubesZB coordinator from Delaware is stuck in a DAI shipping quagmire, which is always the case with those useless amateurs, and is dead to me. It'll probably arrive broken anyway in a few weeks from now, despite being in Melbourne for a week so far. Alternate from Dailedin didn't ship express post on Thursday as expected, but rather last Friday. Given they are in the same city as me but no store pick-up is available, I await the postie Monday.

**Comment by geoffwatts** [comment]
Hey I'm excited at least to have you getting hardware. Can commiserate with
your parcel, at least you're not in WA, which is definitely the end of the
cul-de-sac as far as international shipping goes!

I haven't had time to play with cbus/zigbee for the past week, but
anticipate next week I'll be back to the critical issue that is home
automation.

Having said that, it's mostly been behaving itself, and no moans from the
family - temperatures seem to be updating onto EDLTs, and I've only noticed
one weirdness which (i think) is coming from scenes, ignorecbus and the
event not coming from the bus (rather than the scene), and the group is
still being ignored.

**Comment by autoSteve** [comment]
I think this one is a done deal, @geoffwatts. I've not yet faulted it, but will remain ramping at bed time to monitor. Setting from scene to transition off is what I do here, so that'll get tested well.
